### ISSUE TITLE
安装过程问题

### ISSUE THREAD

**Issue by moon-zhangyue** [studygolang/studygolang#165]
你好,安装时log记录日志
goroutine 1 [running]:
html/template.Must(...)
	C:/Program Files/Go/src/html/template/template.go:374
github.com/studygolang/studygolang/logic.init()
	D:/go/src/studygolang/logic/email.go:142 +0x1185
load config file error: open D:\go\/config/env.ini: The system cannot find the path specified.
get mysql config error: section 'mysql' not found
2021/07/16 15:45:31 config parse redis section error: section 'redis' not found
panic: open D:\go\/template/email.html: The system cannot find the path specified.

这mysql和redis在那里配置呢?   看别的issue提到的新版本在哪里呢?

**Comment by wonderwander** [comment]
panic: open D:\go/template/email.html: The system cannot find the path specified
watch out the panic info, if you debug the application, you can get the problem from the config package
```go
var (
	ConfigFile *goconfig.ConfigFile

	ROOT string // the key is the ROOT var

	TemplateDir string
)

func init() {
	curFilename := os.Args[0]
	binaryPath, err := exec.LookPath(curFilename)
	if err != nil {
		panic(err)
	}

	binaryPath, err = filepath.Abs(binaryPath)
	if err != nil {
		panic(err)
	}

	ROOT = filepath.Dir(filepath.Dir(binaryPath))

	configPath := ROOT + mainIniPath
        // if the configfile does not exist, it will be assign new value to `ROOT`
	if !fileExist(configPath) {
		curDir, _ := os.Getwd()
                // the key is here, it will filter the `src` string, so if your project workspace directory, it will be error and exit, if you r workspace directory include the wrong `src` path or multiple `src` str, it still be error and exit
                // so the correct path your need is : $YourWorkSpcae/src/`your source code of go`, and the `config, template etc folders need be in the root of the $YourWorkSpace,  and then it will be recognize the correct folder, and then you will open the install page
		pos := strings.LastIndex(curDir, "src")
		if pos == -1 {
			// panic("can't find " + mainIniPath)
			fmt.Println("can't find " + mainIniPath)
		} else {
			ROOT = curDir[:pos]

			configPath = ROOT + mainIniPath
		}
	}

	TemplateDir = ROOT + "/template/"

	ConfigFile, err = goconfig.LoadConfigFile(configPath)
	if err != nil {
		// panic(err)
		fmt.Println("load config file error:", err)
		ConfigFile, _ = goconfig.LoadFromData([]byte(""))
	}

	if err = loadIncludeFiles(); err != nil {
		panic("load include files error:" + err.Error())
	}

	go signalReload()
}
```

read the comment of the code block
two solution of this bug:
1. change the project structure, create the new src folder in the project workspace and then move the go source code to the src folder
2. implement the config package in your own project.    the config package url:   https://github.com/polaris1119/config
