### ISSUE TITLE
website_setting方面panic了

### ISSUE THREAD

**Issue by nicle-lin** [studygolang/studygolang#29]
### 我按照你的指南
* 第一，执行db.sql， init.sql
* 第二，设置env.ini中的mysql, redis
* 第三, 执行install.sh(这里有个bug,已解决)
* 第四，执行start.sh, 然后访问http://localhost:8088/，panic了，堆栈信息如下

### please help me
```
[^[[31mPANIC RECOVER^[[0m] runtime error: invalid memory address or nil pointer dereference goroutine 44 [running]:
vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x1000, 0xa10000, 0xeb0420, 0xc42576f200)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/labstack/echo/middleware/recover.go:64 +0x134

panic(0xabece0, 0xeed8c0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
logic.IndexLogic.FindData(0x7f285c5136a8, 0xc42576f200, 0xc42190e8b8, 0x2, 0xc42576f200)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/logic/index.go:31 +0x282
http/controller.IndexController.NewIndex(0xeb0420, 0xc42576f200, 0xb70b3a, 0x5)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/http/controller/index.go:48 +0x1d6
http/controller.(IndexController).NewIndex-fm(0xeb0420, 0xc42576f200, 0xb70b3a, 0x5)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/http/controller/index.go:31 +0x3b
vendor/github.com/labstack/echo.(*Echo).add.func1(0xeb0420, 0xc42576f200, 0x0, 0x0)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/labstack/echo/echo.go:471 +0x90
http/middleware.AutoLogin.func1.1(0xeb0420, 0xc42576f200, 0x0, 0x0)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/http/middleware/login.go:61 +0x212
http/middleware.HTTPError.func1.1(0xeb0420, 0xc42576f200, 0xc4243d39e8, 0xc431f88348)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/http/middleware/http_error.go:22 +0x46
http/middleware.Installed.func1.1(0xeb0420, 0xc42576f200, 0x1000, 0xa10000)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/http/middleware/installed.go:38 +0x101
vendor/github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0xeb0420, 0xc42576f200, 0x0, 0x0)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/labstack/echo/middleware/recover.go:71 +0xa2
vendor/github.com/polaris1119/middleware.EchoLogger.func1.1(0xeb0420, 0xc42576f200, 0x0, 0x0)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/polaris1119/middleware/logger.go:72 +0x566
vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0xeb0420, 0xc42576f200, 0xc42576f200, 0x40e368)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/labstack/echo/echo.go:553 +0x157
vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc420200280, 0xead420, 0xc429d082c0, 0xeab0e0, 0xc425809da0)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/labstack/echo/echo.go:562 +0x1cb
vendor/github.com/labstack/echo/engine/standard.(*Server).ServeHTTP(0xc4201dea00, 0xea7880, 0xc4352ae0e0, 0xc4201e0c00)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/labstack/echo/engine/standard/server.go:138 +0x359
net/http.serverHandler.ServeHTTP(0xc4202440b0, 0xea7880, 0xc4352ae0e0, 0xc4201e0c00)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420428320, 0xea8380, 0xc4201169c0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 1 [select]:
vendor/github.com/facebookgo/grace/gracehttp.Serve(0xc4201d4500, 0x1, 0x1, 0x0, 0x0)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/vendor/github.com/facebookgo/grace/gracehttp/http.go:162 +0x5e6
main.gracefulRun(0xc4201dea00)
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/server/studygolang/graceful_unix.go:13 +0x6d
main.main()
        /home/gubl/web/shipyard/src/github.com/studygolang/studygolang/src/server/studygolang/main.go:79 +0x63e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
vendor/github.com/polaris1119/config.signalReload()
        /home/gubl
{"time":"2017-08-05T21:54:32+08:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"230","message":"runtime error: invalid memory address or nil pointer dereference"}

```

**Comment by polaris1119** [comment]
需要在管理后台：设置->导航 中配置首页导航

**Comment by nicle-lin** [comment]
### 大佬，这个项目不错，能否写个详细点的上部署文档？
### please

**Comment by polaris1119** [comment]
好的，前段时间刚进行了一个大改版，部署方面确实没有测试。我会尽快补充。

**Comment by nicle-lin** [comment]
谢谢
